### ISSUE TITLE
Time and distance estimates are miscalculated at the time of navigation along a route. 

### ISSUE THREAD

**Issue by sebastian-barra-jalafund** [CampusDelSaber/hermes#210] opened 2023-06-29 23:34 UTC
**Describe the bug**
When you start navigating to a point along a route you will notice that the estimated times and distance estimates are incorrect as they show unrealistic data.

**To Reproduce**

1. Open the Hermes application.
2. Login if you are not logged in.
3. Verify that the gps is enabled.
4. Select a location on the map and click on the navigate option.

**Expected behavior**
Realistic estimated times and estimated distances should be displayed according to the user's current position. 

**Screenshots**
![Screenshot from 2023-06-29 19-34-10](https://github.com/CampusDelSaber/hermes/assets/134614219/998a4a2e-d2de-4be1-bf5f-86ecc36cd4fa)

**Smartphone :**
- Device: Xiaomi Redmi Note 9 Pro
- OS: Android
- Version: 11

**Comment by zrock-dev** [comment] 2023-06-30 01:55
duplicate of #198

**Closed as completed** 2023-06-30 01:56 UTC
Labels: bug, Severity 3, team-a
